### PR TITLE
Update chameo.ttl

### PR DESCRIPTION
**Pull request by jsimonclark**
Added techniques that are essential for battery / electrochemical characterization:
- DirectCurrentInternalResistance
- EnergyDispersiveXraySpectroscopy
- FourierTransformInfraredSpectroscopy
- ThreePointBendingTest
- BrunauerEmmettTellerMethod
- MercuryPorosimetry
- PotentiostaticIntermittentTitrationTechnique
- PseudoOpenCircuitVoltageMethod
- StaircaseGalvanostaticIntermittentTitrationTechnique
- XrayDiffraction
- XrayPowderDiffraction

Changed the IRI for GITT to GalvanostaticIntermittentTitrationTechnique

### CODE REVIEW

**Comment by pierluigidelnostro** [comment]
The classes below seem to be too specific to be subClassOf CharacterisationMethod

chameo:MercuryPorosimetry rdf:type owl:Class ;
	rdfs:subClassOf chameo:CharacterisationMethod ;

chameo:BrunauerEmmettTellerMethod rdf:type owl:Class ;
	rdfs:subClassOf chameo:CharacterisationMethod ;

if they cannot be grouped under an existing category of methods can you please suggest a new one?

**Comment by pierluigidelnostro** [comment]
> The classes below seem to be too specific to be subClassOf CharacterisationMethod
> 
> chameo:MercuryPorosimetry rdf:type owl:Class ; rdfs:subClassOf chameo:CharacterisationMethod ;
> 
> chameo:BrunauerEmmettTellerMethod rdf:type owl:Class ; rdfs:subClassOf chameo:CharacterisationMethod ;
> 
> if they cannot be grouped under an existing category of methods can you please suggest a new one?

@jsimonclark Any suggestions for a class to group those?

**Comment by jsimonclark** [comment]
@pierluigidelnostro , yes thanks for the reminder. I suggest to group them under Porosimetry in the following way:

CharacterisationMethod
└── Porosimetry
    ├── MercuryPorosimetry
    └──GasAdsorptionPorosimetry
         └── BrunauerEmmettTellerMethod

I have addd terms for `Porosimetry` and  `GasAdsorptionPorosimetry` , and pushed these changes.

**Comment by jsimonclark** [comment]
@pierluigidelnostro , I resolved the conflicts with the main branch and fixed the issues that were causing emmo check to fail. Could you please have a look and merge if you agree?

**Pull request merged**
